language: node_js
services:
  - redis-server
addons:
  apt:
    packages:
      - redis-server
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install -g jsdoc
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/benchmark.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos.js
env:
  secure: "qdWRQ/LplXqusofcyIw62yackFniv4xQLUQM9GuE9GC4wjhKk6eGFEJmA6Ux6UR/1VZOdAkn3llGPyiS7VeTSzFDXgyW7pgDjMVVxkW0O6jUi/FQcxtXbUQPRq97FzD2BhJp2vEr25QkcpOTUtwQ8Yek+Z1sQiIFzF8EFnzfOBTVsCqBKugFfPSNnB9lNGz/RgRR0h2A0qbpiM2HwQvNribwEFcOiC7zZL/9j+3sRXESGmTP9pEG/5OnDNi0znkc2GxyCvmu1ZGPZ+ZFVaGnqYB+nEODV8oom/wkPYSUkO6h7BhE+F69bVBUTYdQGqd71B2fw20vr7k+i7plJbkMdTzanDU9BXOJsLFI73zm0jC46WuXpmkcuoCWL056UCqnVHeVzbaooLClx20fe6LIG8W+JErKs7AHCZgNpQCvGgpU8MSiGrneTUKlAWuMxE7SeW4HctRRH4QjEYRwsoTa4jRbBVrGY1NTugWCpwY681wnqaT0zJ0WPLJewQDu/iSEKbSMk/dM8jiSwUdC7WqX8mohT4bHAc+2oXyW+JAYJv6+3Xy8qP8KCQTKbU01XJMSTO3HPq62oMRgYAktiqqfPElpvabuiqIoH41pbZCZloMbTxBhO4lmHnU8ZQ21xESvfSgUsSlWlLvk4OH/IZkD7xdYc07cHCdERqoZO/YG4Eg="
